services:
  ollama:
    build: ./ollama
    container_name: ollama_service
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  api:
    build: .
    container_name: rag_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ./src:/app

volumes:
  ollama_data: